name: Feature request
description: Suggest an idea for this project
labels: ["enhancement"]
assignees: Snowiiii
body:
  - type: checkboxes
    id: duplicate
    attributes:
      label: I've searched existing issues and couldn't find a duplicate.
      description: I confirm this is not a duplicate.
      options:
        - label: I confirm this is not a duplicate.
          required: true
  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: "Example: macOS Big Sur"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Server Software Version/Commit
      description: What Server Software Version/Commit are you using?
      placeholder: "Example: 1.0.0/39b4cb3"
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
